### ISSUE TITLE
Templates V2 Roadmap

### ISSUE THREAD

**Issue by FriedrichWeinmann** [PowershellFrameworkCollective/PSModuleDevelopment#37]
ToDo Checklist for the current, in-progress v2 revamp
 - [ ] Add support for linked templates
- Mandate Version or Minimum Version
- Inherit parameters / Prompt for parameters
- Loop Until user interrupt
 - [ ] Add support for explicitly defined encoding
 - [ ] Add support for encoding detection
 - [ ] Add support for parameter description
 - [x] Add tolerance for legacy objects / deserialized templates
 - [x] Add Template compression
 - [ ] Add defined template runtime variables

 - [ ] Turn default template generation into build step
